name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: npm install
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Install Node.js if not installed
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
          . ~/.nvm/nvm.sh
          nvm install 16
          
          # Install PM2 globally
          npm install -g pm2
          
          # Create project directory if it doesn't exist
          mkdir -p ~/xade-api
          
          # Clone repository if it doesn't exist, otherwise pull latest changes
          if [ ! -d ~/xade-api/.git ]; then
            cd ~/xade-api
            git init
            git remote add origin https://github.com/harshalmadnani/ai-api.git
            git fetch
            git checkout -f main
          else
            cd ~/xade-api
            git pull origin main
          fi
          
          # Install dependencies and restart
          npm install
          pm2 restart xade-api || pm2 start index.js --name xade-api
